### PR TITLE
Better Parallelism

### PR DESCRIPTION
**Pull request by ryanpeach**
I wrote this because parallelism wasn't working on my Windows laptop. So I did some reading and found out, at least on windows, you need to declare your Pool from within a `if __name__=="__main__"` structure in order to prevent recurrent execution. Deap also identifies [other kinds of multiprocessing maps](http://deap.readthedocs.io/en/master/tutorials/basic/part4.html) you may want to pass to it, so now the user has every option to implement parallelism however they want by passing their "map" function to pmap.

Yes, it's divergent from sklearn, but sklearn has a fully implemented special parallelism library for their n_jobs parameters that would be both a challenge and potentially incompatible with deap, so what I have implemented is deap's way of doing things.

### CODE REVIEW

**Comment by rsteca** [comment]
This seems awesome, I will check it out when I have some time. Anyway, I think we should keep the n_jobs parameter since in linux it was working fine, and give the option to the users to use n_jobs (that doesn't work on windows) or pmap. We could throw a warning to windows users that n_jobs won't work on windows.

**Comment by ryanpeach** [comment]
Sound's like a good idea, I have never really tried passing warnings, particularly those that have to do with operating-system specific incompatibilities. Maybe, so we don't have two different variables, we just stick with n_jobs, but we allow the user to pass it mapping functions:

`
if isinstance(self.n_jobs, int):
    if isWindows(): # however this works
        raise Warning()
    p = Pool()
    deap.map = p.map()   # You know what i mean
else:
    deap.map = self.n_jobs
`

**Comment by ryanpeach** [comment]
Do we have any idea what the advantages are of using SCOOP like Deap recommends?

**Comment by ryanpeach** [comment]
So one of the reasons I'm contributing is I'm about to (in the next couple of days at most) use this library for some very high search space (128849018880 possible permutations, 3600 dimensional) computations, and I'm putting it on AWS. I want it to be well distributed. However, something I have run into is that our code saves it's **entire** population history, and that this is a bad thing for these large projects. Furthermore, it would be useful to create a system of checkpoints in case the code needs to be terminated prematurely. So I'm going to make these things best I can soon on top of this.

**Comment by rsteca** [comment]
`Do we have any idea what the advantages are of using SCOOP like Deap recommends?`

I haven't read about it yet.

**Comment by ryanpeach** [comment]
So, yah, I need SCOOP lol, and I need to make it myself. Basically it's useful for distributing your work across multiple machines (like on AWS). I'll send you a pull request update in a bit.

**Comment by ryanpeach** [comment]
I think this works now.

**Comment by rsteca** [comment]
Great! I will check it out when I have some time

**Pull request merged**
