### PR TITLE
Added cv_results. Fixed some documentation.

### PR DESCRIPTION
**Pull request by ryanpeach**
In __init__.py I added cv_results_ based on the logbook generated in _fit. This is a compatability feature with sklearn GridSearch and the like in interest of consistency.

Other than that, I added a test file I used outside of ipython notebook which could eventually use the true python test library, and fixed some errors in the notebook which look like simple version errors.

### CODE REVIEW

**Comment by ryanpeach** [comment]
I'm also working on an upgrade to the newer version of sklearn, fixing the grid_search and cross_validation depreciation. Not a small feat unfortunately. Also, individual_evals would be nice to populate, perhaps even instead of cv_results_.

**Comment by ryanpeach** [comment]
Ok, this is READY. I have done a lot:

1. No more depreciation warnings!
2. cv_results_ is now (though imperfect) much improved with a full genealogy report. A full history is provided at all_history_
3. A new optimization file was added for those familiar with scipy.optimize, without cross validation and without the need for data. This is useful if you just want to optimize a function which returns a score, without data to pass it.
3a. Unfortunately, this means a new file structure as well, which got a little messy on merge. Hopefully it's ok now.
4. In order to prove the merge went ok, we have a new unittest file on the main directory test.py. It does indeed work no problems at all on both python2 and python3.

Let me know if you have any questions or changes!

**Comment by ryanpeach** [comment]
In the future, my hope is that the optimize file can be integrated into the _fit method of the main sklearn code, as to prevent code duplication.

**Comment by ryanpeach** [comment]
When viewing this pull request's changes, you will want to go back to past commits, as all you can see now is the messy merge :/

**Comment by rsteca** [comment]
So, I tried the example that's in the readme:
```
import sklearn.datasets
import numpy as np
import random

data = sklearn.datasets.load_digits()
X = data["data"]
y = data["target"]

from sklearn.svm import SVC
from sklearn.cross_validation import StratifiedKFold

paramgrid = {"kernel": ["rbf"],
             "C"     : np.logspace(-9, 9, num=25, base=10),
             "gamma" : np.logspace(-9, 9, num=25, base=10)}

random.seed(1)

from evolutionary_search import EvolutionaryAlgorithmSearchCV
cv = EvolutionaryAlgorithmSearchCV(estimator=SVC(),
                                   params=paramgrid,
                                   scoring="accuracy",
                                   cv=StratifiedKFold(y, n_folds=4),
                                   verbose=1,
                                   population_size=50,
                                   gene_mutation_prob=0.10,
                                   gene_crossover_prob=0.5,
                                   tournament_size=3,
                                   generations_number=5,
                                   n_jobs=4)
cv.fit(X, y)
```

And I got the following error:

```
NotFittedError                            Traceback (most recent call last)
<ipython-input-2-9446b1aeccef> in <module>()
     28                                    generations_number=5,
     29                                    n_jobs=4)
---> 30 cv.fit(X, y)

sklearn-deap/evolutionary_search/cv.pyc in fit(self, X, y)
    331         if self.refit:
    332             self.best_estimator_ = clone(self.estimator)
--> 333             self.best_estimator_.set_params(**self.best_params_)
    334             self.best_estimator_.fit(X, y)
    335 

python2.7/site-packages/sklearn/model_selection/_search.pyc in best_params_(self)
    646     @property
    647     def best_params_(self):
--> 648         check_is_fitted(self, 'cv_results_')
    649         return self.cv_results_['params'][self.best_index_]
    650 

python2.7/site-packages/sklearn/utils/validation.pyc in check_is_fitted(estimator, attributes, msg, all_or_any)
    688     if not all_or_any([hasattr(estimator, attr) for attr in attributes]):
    689         # FIXME NotFittedError_ --> NotFittedError in 0.19
--> 690         raise _NotFittedError(msg % {'name': type(estimator).__name__})
    691 
    692 

NotFittedError: This EvolutionaryAlgorithmSearchCV instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

```

Has something changed in the way you have to call the EvolutionaryAlgorithmSearchCV class?

**Comment by ryanpeach** [comment]
First and foremost, StatefiedKFold will not work in the old style. It now just takes the number of splits. My guess is by using the old StratefyKFold you have somehow broken out of the for loop for training after 0 iterations, and the a not fitted error was raised. Might want to create an explicit assertion warning for that.

Otherwise, thank you for the pep changes, do you have a tool for that?

Also, is my test.py unittest working? You should be able to get the readme test to work by looking at that.

**Comment by ryanpeach** [comment]
At some point I'll go through all these closed issues and create warnings or exceptions for them that describe common fixes.

**Comment by rsteca** [comment]
I tried with the class from model_selection but it doesn't work either. The error occurs when you set a n_jobs greater than 1.
I looked at the code and I see that you deleted this lines:
```
self.best_score_ = float("-inf")
self.best_params_ = None

...

if current_best_score_ > self.best_score_:
            self.best_score_ = current_best_score_
            self.best_params_ = current_best_params_
``` 
This lines are the ones that make the class remember which was the best parameters fitted in the model across all iterations. I tried adding them again but I get a "can't set attribute error". Do you have any idea why is this?

```
Otherwise, thank you for the pep changes, do you have a tool for that?
```
Yes, I use the pep8 sublime linter

**Comment by ryanpeach** [comment]
Hah, yah, that's part of the new sklearn base class now.

best_score and best_params are now properties (you cant set them, they are calculated on query) which are calculated based on cv_results_. Please do not re-add.

**Comment by ryanpeach** [comment]
Am I correct to say that njobs does not work in the original anyway? Yes come to think of it that would cause some problems writing to cv_results_... Does deap support njobs?

**Comment by ryanpeach** [comment]
If test runs, I'm done!

**Comment by rsteca** [comment]
Cool! I ran the tests and everything seems to be working. I'm merging this pull request. Thanks for contributing to this library!!

**Comment by ryanpeach** [comment]
Great, thanks!

**Comment by kootenpv** [comment]
@ryanpeach This is an impressive commitment to seeing this through :) Thanks a lot, cannot wait to give it a try!

**Comment by ryanpeach** [comment]
Impressive what you can do when inspired by personal necessity lol.

**Pull request merged**
