### PR TITLE
Issue27 [Untested]

### PR DESCRIPTION
**Pull request by ryanpeach**
Try this to get the first evaluation, also added the selection to capture all available data.

Is someone willing to test this?

### CODE REVIEW

**Comment by ryanpeach** [comment]
I did this from the web, I don't have access to a test environment at the moment and wont have time for a while to run it, so I'll just leave this here since it's pretty simple now that I think about it.

**Comment by ClimbsRocks** [comment]
Thanks for this! i'll try testing it out later today.

**Comment by rsteca** [comment]
I tried it out but it doesn't seem to work for me. I get the following error:

AttributeError: 'numpy.float64' object has no attribute 'history_index'

**Comment by ryanpeach** [comment]
Ok I'll check it out now.

**Comment by ryanpeach** [comment]
So you're right, you can't use the evaluation history decorator. But I have updated the notebook to make things a little more clear :)

**Pull request merged**
